services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - energy-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    # This port exposes Kafka to the host machine for external clients
    ports:
      - "9092:9092"
    environment:
      # General Broker Configuration
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      # Listeners (Internal & External)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:9093
      # Advertised Listener: MUST use the service name ('kafka') for inter-container communication
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # Security & Quorum Configuration (KRaft specific)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # Other essential settings
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false" # Set to false to manage topics explicitly
    # The default command runs the Kafka server
    # command: ["/bin/sh", "-c", "exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties"]
    # healthcheck ensures the container is ready before dependent services start
    healthcheck:
      test:
        [
          "CMD",
          "/opt/kafka/bin/kafka-broker-api-versions.sh",
          "--bootstrap-server",
          "kafka:9092",
        ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    # volumes:
    # - ./kafka-data:/tmp/kraft-combined-logs # Uncomment for persistent data
    networks:
      - energy-network

  kafka-init:
    # Use a compatible Kafka image for CLI tools
    image: apache/kafka:latest
    container_name: kafka-init
    # Ensure this service only starts after the 'kafka' broker is healthy
    depends_on:
      kafka:
        condition: service_healthy
    # This command creates the 'raw-energy-data' and 'processed-energy-data' topics
    command:
      [
        "/bin/sh",
        "-c",
        "sleep 5 && /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic raw-energy-data --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 && sleep 5 && /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic processed-energy-data --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1",
      ]
    networks:
      - energy-network

  energy_simulator:
    build:
      context: ./realtime_simulator
    container_name: energy_simulator
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    # volumes:
    #   - ./:/app
    # environment:
    #   KAFKA_BROKER: kafka:9092
    #command: python energy_simulator.py
    networks:
      - energy-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: energy-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - energy-network

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=energy-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=2
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_webhdfs_enabled=true
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./data:/data
    networks:
      - energy-network

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=2
    volumes:
      - datanode1-data:/hadoop/dfs/data
    networks:
      - energy-network

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    depends_on:
      - namenode
    ports:
      - "9865:9864"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=2
    volumes:
      - datanode2-data:/hadoop/dfs/data
    networks:
      - energy-network

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    depends_on:
      - namenode
    ports:
      - "9866:9864"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=2
    volumes:
      - datanode3-data:/hadoop/dfs/data
    networks:
      - energy-network

  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8081:8080"
      - "7077:7077"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./data:/data
    networks:
      - energy-network

  spark-worker1:
    image: apache/spark:3.5.3
    container_name: spark-worker1
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./data:/data
    networks:
      - energy-network

  spark_streaming:
    build:
      context: ./realtime_processing
    container_name: spark_streaming
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      cassandra-init:
        condition: service_completed_successfully
    # volumes:
    #   - ./:/opt/spark/app
    # environment:
    #   KAFKA_BROKER: kafka:9092
    # command:
    #   [
    #     "/opt/spark/spark-submit",
    #     "--packages",
    #     "org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.0",
    #     "spark_streaming.py",
    #   ]
    networks:
      - energy-network

  spark-worker2:
    image: apache/spark:3.5.3
    container_name: spark-worker2
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./data:/data
    networks:
      - energy-network

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=energy-cluster
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./cassandra:/cassandra
    networks:
      - energy-network

  cassandra-init:
    image: cassandra:4.1
    container_name: cassandra-init
    depends_on:
      - cassandra
    volumes:
      - ./cassandra:/cassandra
    entrypoint: ["/bin/bash", "-lc"]
    command: >
      "echo 'Waiting for Cassandra...' &&
       for i in {1..60}; do cqlsh cassandra 9042 -e 'DESCRIBE KEYSPACES;' && break || sleep 2; done &&
       cqlsh cassandra 9042 -f /cassandra/schema.cql &&
       echo 'Cassandra schema applied.'"
    networks:
      - energy-network
    
  metastore-db:
    image: postgres:15
    container_name: metastore-db
    environment:
      POSTGRES_DB: metastore_db
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
    volumes:
      - metastore-db-data:/var/lib/postgresql/data
    networks:
      - energy-network

  hive-metastore:
    image: apache/hive:standalone-metastore-4.2.0
    container_name: hive-metastore
    depends_on:
      - metastore-db
      - namenode
    ports:
      - "9083:9083"
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://metastore-db:5432/metastore_db
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hivepassword
        -Dhive.metastore.warehouse.dir=/user/hive/warehouse
    volumes:
      - ./hadoop-conf:/etc/hadoop/conf
      - ./trino/etc:/etc/trino
      - ./hive/ext-jars:/tmp/ext-jars
    networks:
      - energy-network

  trino:
    image: trinodb/trino:478
    container_name: trino
    depends_on:
      - hive-metastore
      - cassandra
      - namenode
    ports:
      - "8082:8080"   # host 8080 is already used by kafka-ui in your compose
    volumes:
      - ./trino/etc:/etc/trino
      - ./hadoop-conf:/etc/hadoop/conf
      - ./trino/sql:/sql
    networks:
      - energy-network
      
networks:
  energy-network:
    driver: bridge

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:
  datanode3-data:
  cassandra-data:
  metastore-db-data:
